// ---------- painted art: art/level1..16.png (one per world) + art/splash.png ----------
// The background is a painting, drawn every frame as PX_STRIPS horizontal strips. Each
// strip carries the depth the picture has at that height (PXD, measured once by
// tools/gen_parallax.py with Depth-Anything), so when the bee crosses the screen the
// flowers at the bottom slide further than the hills at the horizon. The world answers
// the player; nothing in it moves on its own. Ship-wise this replaced the LTX video loops
// on 2026-09-01: 19 MB of clips, three decoders resident, and a stack of iOS play()
// workarounds, for a picture that shimmered in place and never moved with you.
// A decoded 896x1344 background is 4.8 MB of RGBA however small the file is, so only the
// live world and its neighbours stay resident (sliding window).
const ART={},ARTWIN=1;
function artLoad(k){if(ART[k]!==undefined)return;ART[k]=null;const im=new Image();
 im.onload=()=>{ART[k]=im;};im.onerror=()=>{if(!im._freed){ART[k]=null;missing('art/'+k+'.png');}};im.src='art/'+k+'.png';}
function artRelease(k){const im=ART[k];if(im){im._freed=1;im.src='';if(im._mips)im._mips.length=0;}delete ART[k];}
function artSync(){const c=(stage-1)%NL+1,want=new Set(['splash','worlds']);
 for(let d=0;d<=ARTWIN;d++){want.add('level'+((c-1+d)%NL+1));want.add('level'+((c-1-d+NL*2)%NL+1));}
 for(const k of want)artLoad(k);
 for(const k in ART)if(!want.has(k))artRelease(k);
 bossSprSync();}
artLoad('splash');artLoad('worlds');   // 16 world thumbnails for the title's comb
// PXD-BEGIN (generated by tools/gen_parallax.py -- do not edit by hand)
const PXD={1:[0,0.01,0.02,0.04,0.07,0.09,0.13,0.16,0.19,0.21,0.23,0.25,0.26,0.28,0.3,0.33,0.38,0.44,0.48,0.51,0.52,0.53,0.55,0.59,0.62,0.66,0.69,0.75,0.81,0.89,0.96,1],2:[0,0,0,0.01,0.01,0.02,0.04,0.07,0.12,0.17,0.23,0.29,0.35,0.4,0.43,0.46,0.49,0.53,0.58,0.62,0.64,0.65,0.66,0.67,0.7,0.74,0.78,0.83,0.88,0.92,0.97,1],3:[0,0,0.01,0.01,0.01,0.02,0.02,0.03,0.04,0.06,0.07,0.09,0.11,0.13,0.16,0.19,0.23,0.27,0.31,0.36,0.41,0.47,0.52,0.56,0.61,0.66,0.72,0.79,0.86,0.92,0.97,1],4:[0.4,0.45,0.47,0.46,0.45,0.47,0.47,0.49,0.52,0.59,0.65,0.67,0.63,0.52,0.35,0.17,0.04,0,0.03,0.08,0.13,0.19,0.26,0.36,0.46,0.56,0.64,0.71,0.78,0.86,0.94,1],5:[0,0.02,0.05,0.08,0.08,0.07,0.07,0.08,0.09,0.07,0.05,0.02,0.01,0.02,0.04,0.08,0.13,0.18,0.23,0.27,0.31,0.35,0.4,0.45,0.51,0.58,0.65,0.72,0.79,0.87,0.94,1],6:[1,0.97,0.93,0.88,0.82,0.76,0.7,0.62,0.54,0.46,0.39,0.31,0.22,0.14,0.07,0.03,0,0,0,0.02,0.04,0.07,0.11,0.17,0.23,0.27,0.3,0.31,0.31,0.29,0.27,0.25],7:[0,0,0.01,0.02,0.05,0.09,0.14,0.17,0.19,0.21,0.24,0.27,0.3,0.33,0.36,0.38,0.41,0.45,0.48,0.52,0.54,0.58,0.61,0.64,0.68,0.73,0.77,0.82,0.87,0.91,0.96,1],8:[0,0.01,0.03,0.07,0.12,0.17,0.21,0.26,0.3,0.33,0.36,0.39,0.42,0.44,0.46,0.49,0.51,0.54,0.57,0.6,0.63,0.66,0.69,0.72,0.75,0.78,0.81,0.85,0.89,0.93,0.97,1],9:[0.81,0.95,1,0.98,0.86,0.77,0.72,0.71,0.72,0.7,0.65,0.64,0.66,0.73,0.76,0.73,0.62,0.47,0.29,0.18,0.2,0.32,0.4,0.35,0.19,0.05,0,0.02,0.07,0.1,0.12,0.13],10:[0.94,0.89,0.81,0.73,0.64,0.53,0.41,0.29,0.2,0.15,0.14,0.13,0.12,0.11,0.11,0.1,0.08,0.06,0.03,0.01,0,0.02,0.06,0.12,0.19,0.27,0.38,0.49,0.62,0.76,0.9,1],11:[0,0,0.01,0.01,0.02,0.03,0.04,0.05,0.06,0.08,0.1,0.12,0.13,0.15,0.17,0.21,0.26,0.31,0.37,0.44,0.52,0.57,0.61,0.65,0.72,0.83,0.95,1,0.99,0.93,0.88,0.84],12:[0,0,0.01,0.02,0.03,0.05,0.07,0.09,0.1,0.11,0.13,0.16,0.19,0.23,0.28,0.32,0.36,0.4,0.44,0.47,0.52,0.56,0.61,0.65,0.7,0.74,0.78,0.82,0.86,0.91,0.96,1],13:[0,0,0,0.01,0.03,0.06,0.09,0.12,0.16,0.2,0.24,0.28,0.32,0.36,0.39,0.43,0.46,0.49,0.53,0.57,0.61,0.65,0.68,0.72,0.76,0.79,0.83,0.86,0.9,0.93,0.97,1],14:[0,0,0.02,0.04,0.08,0.12,0.15,0.19,0.22,0.26,0.29,0.32,0.35,0.38,0.41,0.45,0.49,0.54,0.58,0.62,0.65,0.67,0.69,0.71,0.75,0.8,0.84,0.88,0.91,0.94,0.98,1],15:[0,0.06,0.15,0.23,0.29,0.31,0.31,0.31,0.3,0.3,0.31,0.32,0.35,0.41,0.48,0.55,0.61,0.66,0.69,0.71,0.73,0.75,0.78,0.8,0.83,0.85,0.88,0.9,0.92,0.95,0.98,1],16:[0.3,0.35,0.36,0.36,0.33,0.29,0.26,0.22,0.19,0.17,0.15,0.13,0.11,0.09,0.07,0.05,0.04,0.02,0.01,0,0.01,0.06,0.14,0.26,0.38,0.49,0.59,0.69,0.77,0.86,0.94,1],splash:[0,0.01,0.03,0.04,0.05,0.06,0.06,0.05,0.03,0.01,0.06,0.21,0.47,0.74,0.93,1,0.97,0.88,0.78,0.7,0.63,0.55,0.45,0.33,0.23,0.18,0.17,0.2,0.25,0.33,0.39,0.44]};
// PXD-END
// PX_X: how far the nearest strip slides when the bee is at the screen edge (css px).
// PX_Y: the slow breathing of the nearest strip, ±px over ~25 s -- the picture's pulse,
// far below anything that could read as something to dodge. LOW mode draws the plain still.
const PX_STRIPS=32,PX_X=22,PX_Y=6;
function splashFrame(){return ART.splash;}
const SPR={},MISSING=[];
// A 768px boss sprite is 2.4 MB decoded. All sixteen were resident for the one actually
// fighting you. Keep the current world's boss and its neighbours; drop the rest.
function bossSprLoad(i){const k='boss'+i;if(SPR[k]!==undefined)return;SPR[k]=null;
 const im=new Image();im.onload=()=>{SPR[k]=im;};im.onerror=()=>{if(!im._freed){SPR[k]=null;missing('art/sprites/'+k+'.png');}};im.src='art/sprites/'+k+'.png';}
function bossSprSync(){const want=new Set();
 for(let d=0;d<=ARTWIN;d++){want.add(THEMES[((stage-1)%NL+d)%NL].boss);want.add(THEMES[((stage-1)%NL-d+NL*2)%NL].boss);}
 for(const i of want)bossSprLoad(i);
 for(const k in SPR){const m=/^boss(\d+)$/.exec(k);
  if(m&&!want.has(+m[1])){const im=SPR[k];if(im){im._freed=1;im.src='';if(im._mips)im._mips.length=0;}delete SPR[k];}}}
function missing(path){MISSING.push(path);console.warn('[hive-strike] asset missing:',path);}
function loadSprites(){const names=Object.keys(ET).concat(['centihead1','centiseg1','hero']);/* hero = the painted player bee */for(const k of names){const im=new Image();im.onload=()=>{SPR[k]=im;};im.onerror=()=>missing('art/sprites/'+k+'.png');im.src='art/sprites/'+k+'.png';}}
// sprites are ~800px tall and get drawn at 35-80px. drawImage has no mipmaps, so that 12-25x
// downscale shimmered every frame as the bug moved. halve the source until it is close to the
// drawn size, cache each step, and the final draw is never worse than a 2x reduction.
function mip(im,h){const need=h*DPR*1.4;if(!im.height||im.height<need*2)return im;
 // Four places empty this array rather than deleting it -- rasterReset() when the raster
 // scale changes, and artRelease/bossSprSync when a level slides out of the
 // window. An emptied array is still truthy, so the old `if(!im._mips)` did not re-seed
 // it, cur came back undefined, and `cur.height` threw. That killed the frame loop and
 // froze the game with the music still playing (iPhone, 2026-08-27). Re-seed on EMPTY,
 // not just on missing.
 if(!im._mips||!im._mips.length)im._mips=[im];let cur=im._mips[im._mips.length-1];
 while(cur.height>need*2&&cur.height>2){const c=document.createElement('canvas');c.width=Math.max(1,cur.width>>1);c.height=Math.max(1,cur.height>>1);const g=c.getContext('2d');g.imageSmoothingEnabled=true;g.imageSmoothingQuality='high';g.drawImage(cur,0,0,c.width,c.height);im._mips.push(c);cur=c;}
 for(let i=im._mips.length-1;i>=0;i--)if(im._mips[i].height>=need)return im._mips[i];
 return im._mips[0];}
function drawSprite(im,h,rot=0){const m=mip(im,h),sc=h/m.height,w=m.width*sc;X.save();X.rotate(rot);X.drawImage(m,-w/2,-h/2,w,h);X.restore();}
function drawArt(im,alpha=1,px=null){const iw=im.width,ih=im.height;if(!iw||!ih)return;
 const over=px&&!LOW?1+2*PX_X/W:1,sc=Math.max(W/iw,H/ih)*over,w=iw*sc,h=ih*sc,x0=(W-w)/2,y0=(H-h)/2;
 X.globalAlpha=alpha;
 if(!px||LOW){X.drawImage(im,x0,y0,w,h);X.globalAlpha=1;return;}
 // sideways from the bee in play (title screens get a slow drift), plus the breathing
 const dx=state==='play'?-(P.x-W/2)/(W/2)*PX_X:Math.sin(t*.004)*PX_X*.5,dy=Math.sin(t*.0042)*PX_Y;
 const n=px.length,sh=ih/n,ov=4;   // source rows per strip; overscan so no seam ever opens
 for(let i=0;i<n;i++){const d=px[i],a=Math.max(0,i*sh-ov),b=Math.min(ih,(i+1)*sh+ov);
  X.drawImage(im,0,a,iw,b-a,x0+dx*d,y0+a*sc+dy*d,w,(b-a)*sc);}
 X.globalAlpha=1;}
